export const dataSourcesMappings = {'ru_acf_bribetakers': 'ACF List of War Enablers',
'afdb_sanctions': 'African Development Bank Debarred Entities',
'ar_parliament': 'Argentina Members of Parliament',
'ar_repet': 'Argentina RePET Sanctions',
'am_hetq_officials': 'Armenia Public Officials and Associates',
'adb_sanctions': 'Asian Development Bank Sanctions',
'au_dfat_sanctions': 'Australian Sanctions Consolidated List',
'AU-DPRK': 'Democratic People\'s Republic Of Korea (North Korea) Sanctions Regime',
'AU-YUGO': 'Former Federal Republic Of Yugoslavia Sanctions Regime',
'AU-IRAN': 'Iran Sanctions Regime',
'AU-IRAQ': 'Iraq Sanctions Regime',
'AU-LIBYA': 'Libya Sanctions Regime',
'AU-MYANMAR': 'Myanmar Sanctions Regime',
'AU-RUSSIA': 'Russia Sanctions Regime',
'AU-CRP': 'Serious Corruption Sanctions Regime',
'AU-HUMAN': 'Serious Violations Or Serious Abuses Of Human Rights Sanctions Regime',
'AU-CYB': 'Significant Cyber Incidents Sanctions Regime',
'AU-UKRAINE-REG': 'Specified Ukraine Regions Sanctions Regime',
'AU-SYRIA': 'Syria Sanctions Regime',
'AU-UKRAINE': 'Ukraine Sanctions Regime',
'AU-ZIM': 'Zimbabwe Sanctions Regime',
'at_meine_abgeordneten': 'Austria Public Officials',
'at_nbter_sanctions': 'Austrian National Bank Regulations on Terrorism Financing Restrictions',
'az_fiu_sanctions': 'Azerbaijan Domestic List',
'be_fod_sanctions': 'Belgian Financial Sanctions',
'BE-FOD-NAT': 'National list of terrorist suspects whose assets have been frozen',
'br_bcb_prohibited': 'Brazil Entities Prohibited from Offering Auditing Services',
'br_tcu_debarred': 'Brazil List of Debarred Bidders',
'br_tcu_disqualified': 'Brazil List of Individuals Disqualified from Public Service',
'br_ceis': 'Brazil National Register of Disreputable and Suspended Companies',
'br_pep': 'Brazil Politically Exposed Persons',
'br_bcb_disqualified_persons': 'Brazil Register of Persons Disqualified from Senior Roles',
'bg_omnio_poi': 'Bulgarian Persons of Interest',
'iso9362_bic': 'Business Identifier Code (BIC) Reference Data',
'ca_dfatd_sema_sanctions': 'Canadian Consolidated Autonomous Sanctions List',
'CA-JVCFOA': ' Justice For Victims Of Corrupt Foreign Officials Act',
'CA-SEMA': 'Special Economic Measures Act',
'ca_facfoa': 'Canadian Freezing Assets of Corrupt Foreign Officials Act',
'CA-FACFOA-TUN': 'Freezing Assets of Corrupt Foreign Officials (Tunisia) Regulations (SOR/2011-78)',
'CA-FACFOA-UKR': 'Freezing Assets of Corrupt Foreign Officials (Ukraine) Regulations (SOR/2014-44)',
'ca_listed_terrorists': 'Canadian Listed Terrorist Entities',
'ca_named_research_orgs': 'Canadian Named Research Organizations list',
'CA-NRO': 'Policy On Sensitive Technology Research And Affiliations Of Concern',
'ky_parliament': 'Cayman Islands Members of Parliament',
'ky_judicial': 'Cayman Islands Senior Judicial Officers',
'cn_peoples_congress_wikipedia': 'China National People\'s Congress on Wikipedia',
'cn_sanctions': 'China Sanctions Research',
'CN-AFSL': 'Chinese Anti-Foreign Sanctions Law (AFSL)',
'CN-CML': 'Chinese Counter-Measures List',
'CN-UEL': 'Chinese Unreliable Entities List (UEL)',
'co_join_dots': 'Colombian Joining the Dots PEPs',
'co_funcion_publica': 'Colombian PEP Declarations',
'hr_public_officials': 'Croatia State Registry of Public Officials',
'cu_inventario_legislatura': 'Cuba Members of the Parliament',
'ext_cy_companies': 'Cyprus Companies and Corporate Officers',
'ext_cz_business_register': 'Czech Republic Business Register',
'cz_national_sanctions': 'Czech Republic National Sanctions',
'CZ-A1-2023COLL': 'Law On Restrictive Measures Against Certain Serious Acts Applied In International Relations (Act No. 1/2023 Coll.)',
'dk_pep': 'Denmark, Faroe Islands and Greenland PEPs',
'kp_rusi_reports': 'DPRK Reports',
'ebrd_ineligible': 'EBRD Ineligible Entities',
'eg_terrorists': 'Egypt Domestic Terrorist List',
'eiti_soe': 'EITI State-Owned Enterprises Database',
'ext_ee_ariregister': 'Estonia e-Business Register (E-äriregister)',
'ee_international_sanctions': 'Estonia International Sanctions Act List',
'ee_riigikogu': 'Estonia Members of the Riigikogu',
'eu_travel_bans': 'EU Consolidated Travel Bans',
'eu_journal_sanctions': 'EU Council Official Journal Sanctioned Entities',
'EU-2878': 'EU Council Regulation 2023/2878 (Sanctions Related To Russian Aggression Against Ukraine)',
'eu_edes': 'EU Early Detection and Exclusion System (EDES)',
'eu_esma_sanctions': 'EU ESMA Sanctions',
'eu_esma_saris': 'EU ESMA Suspensions and Removals',
'ext_eu_esma_firds': 'EU Financial Instruments Reference Data System (FIRDS)',
'eu_fsf': 'EU Financial Sanctions Files (FSF)',
'EU-US-LEG': 'EU Measures Protecting Against The Effects Of The Extra-Territorial Application Of Certain US Legislation',
'EU-TUNISIA': 'EU Misappropriation of State Funds Of Tunisia (MSF)',
'EU-UKRAINE-MSF': 'EU Misappropriation of State Funds Of Ukraine (MSF)',
'EU-CRNA-UN757': 'EU Montenegro UN Security Council Resolution 757 (1992)',
'EU-SRB-UN757': 'EU Prohibiting The Satisfying Of Certain Claims In Relation To Un Security Council Resolution 757(1992) Serbia',
'EU-CYB': 'EU Restrictive Measures Against Cyber-Attacks Threatening The Union Or Its Member States',
'EU-RIGHTS': 'EU Restrictive Measures Against Serious Human Rights Violations And Abuses',
'EU-HAMAS': 'EU Restrictive Measures Against Supporters Of Hamas And The Palestinian Islamic Jihad',
'EU-SYRIA': 'EU Restrictive Measures Against Syria',
'EU-CHEM': 'EU Restrictive Measures Against The Proliferation And Use Of Chemical Weapons',
'EU-IRAN-HR': 'EU Restrictive Measures In Relation To Serious Human Rights Violations In Iran',
'EU-PMR': 'EU Restrictive Measures In Relation To The Campaign Against Latinscript Schools In The Transnistrian Region',
'EU-WMD': 'EU Restrictive Measures In Relation To The Non-Proliferation Of The Weapons Of Mass Destruction (WMD)',
'EU-UKRAINE-INTEG': 'EU Restrictive Measures In Respect Of Actions Undermining Or Threatening Ukraine (Territorial Integrity)',
'EU-CRIMEA': 'EU Restrictive Measures In Response To The Illegal Annexation Of Crimea And Sevastopol (Crimea)',
'EU-UKRAINE-OCC': 'EU Restrictive Measures In Response To The Illegal Russian Occupation Certain Non-Government Controlled Areas Of Ukraine',
'EU-MOLDOVA': 'EU Restrictive Measures In View Of Actions Destabilising The Republic Of Moldova',
'EU-SUDAN-REST': 'EU Restrictive Measures In View Of Activities Undermining The Stability And The Political Transition Of Sudan',
'EU-IRAN-RUSSIA': 'EU Restrictive Measures In View Of Iran\'s Military Support of Russia\'s War Of Aggression Against Ukraine',
'EU-RUSSIA-REST': 'EU Restrictive Measures In View Of Russia\'s Actions Destabilizing The Situation In Ukraine (Sectoral Restrictive Measures)',
'EU-BOSNIA': 'EU Restrictive Measures In View Of The Situation In Bosnia And Herzegovina',
'EU-BURUNDI': 'EU Restrictive Measures In View Of The Situation In Burundi',
'EU-GUATEMALA': 'EU Restrictive Measures In View Of The Situation In Guatemala',
'EU-GUINEA': 'EU Restrictive Measures In View Of The Situation In Guinea',
'EU-HAITI': 'EU Restrictive Measures In View Of The Situation In Haiti',
'EU-LEBANON': 'EU Restrictive Measures In View Of The Situation In Lebanon',
'EU-LIBYA': 'EU Restrictive Measures In View Of The Situation In Libya',
'EU-MALI': 'EU Restrictive Measures In View Of The Situation In Mali',
'EU-MYANMAR': 'EU Restrictive Measures In View Of The Situation In Myanmar And Burma',
'EU-NICARAGUA': 'EU Restrictive Measures In View Of The Situation In Nicaragua',
'EU-NIGER': 'EU Restrictive Measures In View Of The Situation In Niger',
'EU-SOUTHSUDAN': 'EU Restrictive Measures In View Of The Situation In South Sudan',
'EU-SUDAN': 'EU Restrictive Measures In View Of The Situation In Sudan',
'EU-DRC': 'EU Restrictive Measures In View Of The Situation In The Democratic Republic Of The Congo',
'EU-VEN-REST': 'EU Restrictive Measures In View Of The Situation In Venezuela',
'EU-TURKEY-MED': 'EU Restrictive Measures In View Of Turkey\'s Unauthorized Drilling In The Eastern Mediterranean',
'EU-ISIS': 'EU Restrictive Measures With Respect To ISIL (Da\'esh) And Al-Qaida (ISIL/Daesh & Al-Qaida)',
'EU-TERROR': 'EU Specific Measures To Combat Terrorism',
'EU-TIANANMEN': 'EU Specific Restrictive Measures In Relation To The Events At The Tiananmen Square Protests Of 1989',
'EU-BRUS': 'Restrictive Measures In View Of The Situation In Belarus And The Involvement Of Belarus In The Russian Aggression Against Ukraine',
'eu_public_functions': 'EU Prominent Public Functions',
'eu_sanctions_map': 'EU Sanctions Map',
'eu_europol_wanted': 'Europe Most Wanted Fugitives',
'eu_cor_members': 'European Commitee of the Regions Members',
'eu_meps': 'European Parliament Members',
'everypolitician': 'Every Politician',
'ru_billionaires_2021': 'Forbes 2021 List of Russian Billionaires',
'fr_illegal_financial_services': 'France AMF Illegal Financial Services list',
'fr_amf_regulatory_sanctions': 'France AMF Regulatory sanctions',
'fr_maires': 'French Mayors',
'fr_assemblee': 'French National Assembly',
'fr_tresor_gels_avoir': 'French National Asset Freezing System',
'FR-CMF-562': 'Art L. 562-2 And 562-3 Of The Monetary And Financial Code',
'fr_senat': 'French Senators',
'ge_declarations': 'Georgia Public Official Asset Declarations',
'ge_ot_list': 'Georgian Otkhozoria–Tatunashvili List',
'de_abgeordnetenwatch': 'German Legislators from AbgeordnetenWatch',
'de_bka_wanted': 'Germany BKA Wanted Fugitives',
'gem_energy_ownership': 'Global Energy Ownership Tracker',
'gg_disqualified_directors': 'Guernsey FSC Prohibitions and Disqualified Directors',
'hk_legco': 'Hong Kong Legislative Council Members',
'hk_principal_officials': 'Hong Kong Principal Officials',
'is_althingi': 'Iceland parliament',
'ext_icij_offshoreleaks': 'ICIJ Offshore Leaks Database',
'ICIJ-BA': 'Bahamas Leaks (2016)',
'ICIJ-OL': 'Offshore Leaks (2013)',
'ICIJ-PA': 'Panama Papers (2016)',
'ICIJ-PAP': 'Pandora Papers (2021)',
'ICIJ-PP': 'Paradise Papers (2017)',
'in_nse_debarred': 'India National Stock Exchange Debarred Entities',
'in_mha_banned': 'Indian Ministry of Home Affairs Banned Organizations',
'IN-UAPA': 'Unlawful Activities (Prevention) Act, 1967',
'id_regional_2018': 'Indonesia 2018 Regional Head Election Results',
'id_dttot': 'Indonesian List of Suspected Terrorists and Terrorist Organizations',
'iadb_sanctions': 'Inter-American Development Bank Sanctions',
'interpol_red_notices': 'INTERPOL Red Notices',
'ir_sanctions': 'Iran Sanctions List',
'IR-MFA-SANC': 'Individuals And Entities In The Sanction’s List Of The Islamic Republic Of Iran',
'ir_uani_business_registry': 'Iran UANI Business Registry',
'ie_unlawful_organizations': 'Ireland Unlawful Organisation (Suppression) Orders',
'im_disqualified_directors': 'Isle of Man FSA Disqualified Directors',
'il_knesset_members': 'Israel Knesset Members',
'il_wmd_sanctions': 'Israel Prevention of Distribution and Financing of WMDs designations',
'il_mod_crypto': 'Israel Sanctioned Crypto Wallets List',
'il_mod_terrorists': 'Israel Terrorists Organizations and Unauthorized Associations lists',
'jp_mof_sanctions': 'Japan Economic Sanctions and List of Eligible People',
'jp_meti_eul': 'Japan METI End User List',
'kz_afmrk_sanctions': 'Kazakh Terrorist and Terror Financing lists',
'ext_kz_companies': 'Kazakhstan State Register of legal entities',
'kg_fiu_national': 'Kyrgyz National List',
'lv_fiu_sanctions': 'Latvia FIU Sanctions',
'lv_magnitsky_list': 'Latvia\'s Magnitsky Law Sanctions List',
'lv_saeima': 'Latvian Saeima',
'ext_gleif': 'Legal Entity Identifier (LEI) Reference Data',
'li_entsg': 'Liechtenstein Posted Workers Act (EntsG) Sanctions',
'lt_magnitsky_amendments': 'Lithuania Designated Persons Under Magnitsky Amendments',
'lt_illegal_websites': 'Lithuania Illegal Financial Services',
'lt_illegal_gambling': 'Lithuania Illegal Gambling Operators',
'lt_seimas': 'Lithuania Members of the Seimas',
'lt_pep_declarations': 'Lithuania PEPs from the register of private interests',
'lt_fiu_freezes': 'Lithuanian International Sanctions',
'lu_administrative_sanctions': 'Luxembourg Administrative Sanctions',
'my_consumer_alert_list': 'Malaysia Financial Consumer Alert List',
'my_moha_sanctions': 'Malaysia MOHA Sanctions List',
'my_aob_sanctions': 'Malaysia Securities Commission AOB Enforcements',
'my_investor_alert_list': 'Malaysia Securities Commission Investor Alert List',
'mx_deputies': 'Mexico Chamber of Deputies',
'mx_governors': 'Mexico Governors',
'mx_senators': 'Mexico Senate',
'md_interdictie': 'Moldovan Ban List of Economic Operators',
'md_terror_sanctions': 'Moldovan Sanctions for Terrorism and Proliferation of WMD',
'mc_fund_freezes': 'Monaco National Fund Freezing List',
'ru_navalny35': 'Navalny 35 List of Individuals for Sanctioning',
'np_mha_sanctions': 'Nepal Prohibited Persons or Groups according per National Strategy and Action Plan (2076-2081)',
'nl_terrorism_list': 'Netherlands National Sanctionlist Terrorism',
'nl_most_wanted': 'Netherlands Police Nationale Opsporingslijst',
'nz_designated_terrorists': 'New Zealand Designated Terrorist Entities',
'nz_russia_sanctions': 'New Zealand Russia Sanctions',
'NZ-RSA2022': 'Russia Sanctions Act 2022',
'ng_join_dots': 'Nigeria Joining the Dots PEPs and PEP Relatives',
'ng_nigsac_sanctions': 'Nigeria Sanctions List',
'ng_chipper_peps': 'Nigerian Politically Exposed Persons data by Chipper',
'no_nbim_exclusions': 'Norges Bank Investment Management observation and exclusion of companies',
'mk_officials': 'North Macedonia Elected and Appointed Officials',
'ps_ohchr_settlement': 'OHCHR List of Companies Linked to Illegal Settlement in the West Bank',
'opencorporates': 'OpenCorporates',
'openfigi': 'OpenFIGI Securities Information',
'research': 'OpenSanctions Research Data',
'pk_proscribed_persons': 'Pakistan NACTA Proscribed Persons',
'ps_local_freezing': 'Palestine Monetary Authority Local Freezing List',
'cl_info_probidad': 'PEPs from Chile Interest and Asset Declarations',
'permid': 'PermID Open Data',
'ph_sec_advisories': 'Philippines SEC Advisories',
'ph_most_wanted': 'Philippines Top Most Wanted Persons in the Cordillera Regions',
'pl_mswia_sanctions': 'Polish List of Persons and Entities Subject to Sanctions',
'pl_finanse_sanctions': 'Polish Sanctions Countering Money Laundering and Terror Financing',
'PL-AML118': 'Art. 118 of the Act of March 1, 2018 on counteracting money laundering and terrorism financing',
'qa_nctc_sanctions': 'Qatar Unified Record of Persons and Entities on Sanction List',
'ransomwhere': 'ransomwhe.re ransomware addresses',
'ext_lv_business_register': 'Register of Enterprises of the Republic of Latvia (Uzņēmumu reģistrs)',
'ext_ror': 'Research Organizations Registry',
'md_rise_profiles': 'RISE Moldova People of interest',
'ro_onpcsb_sanctions': 'Romania Government Decision No. 1.272/2005: List of Suspected Terrorists',
'ru_cbr_banks': 'Russia Banking Registry',
'ru_nsd_isin': 'Russian National Settlement Depository (NSD, ISIN Assignment)',
'wd_oligarchs': 'Russian Oligarch/Billionaires Database',
'US-CAATSA2018': 'US Section 241 CAATSA Report (2018)',
'ru_dossier_center_poi': 'Russian Persons of Interest published by Dossier Center',
'ru_myrotvorets_wagner': 'Russian PMC Wagner mercenaries (Myrotvorets list)',
'ext_ru_egrul': 'Russian Unified State Register of Legal Entities (as at Jan 1, 2022)',
'rs_apml_domestic': 'Serbian Domestic List of Designated Persons',
'sg_gov_dir': 'Singapore Government Directory',
'sg_terrorists': 'Singapore Targeted Financial Sanctions',
'SG-TSFA2002': 'Terrorism (Suppression of Financing) Act 2002',
'si_conflicts': 'Slovenia Business Restrictions',
'si_zvezoskop': 'Slovenian Political Officials from Zvezoskop',
'za_mm_officials': 'South Africa Municipal Leadership',
'za_pmg_legislators': 'South Africa National and Provincial Legislators',
'za_fic_sanctions': 'South Africa Targeted Financial Sanctions',
'za_wanted': 'South Africa Wanted Persons',
'es_cnp_wanted': 'Spain National Police Most Wanted List',
'ext_md_companies': 'State Register of legal entities in the Republic of Moldova',
'ch_finma_rulings': 'Swiss FINMA Final Rulings',
'ch_finma_warnings': 'Swiss FINMA Warning List',
'ch_seco_sanctions': 'Swiss SECO Sanctions/Embargoes',
'SECO-ERITREA': 'Former Measures Against Eritrea',
'SECO-CDI': 'Former Measures Against Ivory Coast',
'SECO-LIBERIA': 'Former Measures Against Liberia',
'SECO-YUGO': 'Former Measures Against Yugoslavia',
'SECO-BRUS': 'Measures Against Belarus',
'SECO-BURUNDI': 'Measures Against Burundi',
'SECO-GUINEA': 'Measures Against Guinea',
'SECO-BISSAU': 'Measures Against Guinea Bissau',
'SECO-LIBYA': 'Measures Against Libya',
'SECO-MYANMAR': 'Measures Against Myanmar',
'SECO-NICARAGUA': 'Measures Against Nicaragua',
'SECO-NORTHKOREA': 'Measures Against North Korea',
'SECO-AFGH': 'Measures Against Persons And Organizations With Links To Usama Bin Laden, Al-Qaeda Or The Taliban',
'SECO-SOMALIA': 'Measures Against Somalia',
'SECO-SOUTHSUDAN': 'Measures Against South Sudan',
'SECO-SUDAN': 'Measures Against Sudan',
'SECO-SYRIA': 'Measures Against Syria',
'SECO-CAR': 'Measures Against The Central African Republic',
'SECO-DRC': 'Measures Against The Democratic Republic Of Congo',
'SECO-IRAN': 'Measures Against The Islamic Republic Of Iran',
'SECO-IRAQ': 'Measures Against The Republic Of Iraq',
'SECO-MALI': 'Measures Against The Republic Of Mali',
'SECO-VEN': 'Measures Against Venezuela',
'SECO-YEMEN': 'Measures Against Yemen',
'SECO-ZIM': 'Measures Against Zimbabwe',
'SECO-HAITI': 'Measures In Relation To Haiti',
'SECO-MOLDOVA': 'Measures In relation To Moldova',
'SECO-UKRAINE': 'Measures In Relation To The Situation In Ukraine',
'SECO-HARIRI': 'Measures In Relation With The Rafiq Hariri Assassination',
'SECO-LEB': 'Measures Related To Lebanon',
'sy_obsalytics_opensyr': 'Syrian Observatory of Political and Economic Networks',
'th_cabinet': 'Thailand Cabinet of Ministers',
'th_designated_person': 'Thailand Designated Persons List',
'TH-SEC-7': 'List of designated persons under Section 7',
'thesentry_atlas': 'The Sentry Atlas',
'tr_fcib': 'Türkiye Asset Freezing Sanctions List (MASAK)',
'tr_parliament': 'Türkiye Grand National Assembly',
'tr_wanted': 'Türkiye Ministry Of Interior Terrorist Wanted List',
'us_ice_wanted': 'U.S. Immigration and Customs Enforcement Most Wanted Fugitives',
'gb_coh_disqualified': 'UK Companies House Disqualified Directors',
'ext_gb_coh_psc': 'UK Companies House People with Significant Control',
'gb_fcdo_sanctions': 'UK FCDO Sanctions List',
'GB-SAMLA': 'Sanctions and Anti-Money Laundering Act 2018',
'gb_hmt_sanctions': 'UK HMT/OFSI Consolidated List of Targets',
'UK-FO': 'Financial Sanctions, UK freezing orders',
'UK-CH': 'UK arms embargo on mainland China and Hong Kong',
'UK-AFG': 'UK sanctions relating to Afghanistan',
'UK-AA': 'UK sanctions relating to Armenia and Azerbaijan',
'UK-BH': 'UK sanctions relating to Bosnia and Herzegovina',
'UK-CW': 'UK sanctions relating to chemical weapons',
'UK-CYB': 'UK sanctions relating to cyber activity',
'UK-CT': 'UK sanctions relating to domestic counter-terrorism',
'UK-AC': 'UK sanctions relating to global anti-corruption',
'UK-HR': 'UK sanctions relating to global human rights',
'UK-GU': 'UK sanctions relating to Guinea',
'UK-HT': 'UK Sanctions relating to Haiti',
'UK-ICT': 'UK sanctions relating to international counter-terrorism',
'UK-IRAN': 'UK sanctions relating to Iran',
'UK-IRAN-NW': 'UK sanctions relating to Iran (nuclear weapons)',
'UK-IRQ': 'UK sanctions relating to Iraq',
'UK-ISIL': 'UK sanctions relating to ISIL (Da’esh) and Al-Qaida',
'UK-LEB': 'UK sanctions relating to Lebanon',
'UK-LEB-RH': 'UK sanctions relating to Lebanon (Assassination of Rafiq Hariri and others)',
'UK-LBY': 'UK sanctions relating to Libya',
'UK-MLI': 'UK sanctions relating to Mali',
'UK-MMR': 'UK sanctions relating to Myanmar',
'UK-NIC': 'UK sanctions relating to Nicaragua',
'UK-RUS': 'UK sanctions relating to Russia',
'UK-SOM': 'UK sanctions relating to Somalia',
'UK-SSD': 'UK sanctions relating to South Sudan',
'UK-SDN': 'UK sanctions relating to Sudan',
'UK-SYR': 'UK sanctions relating to Syria',
'UK-SYR-CP': 'UK sanctions relating to Syria cultural property',
'UK-CAR': 'UK sanctions relating to the Central African Republic',
'UK-DPRK': 'UK sanctions relating to the Democratic People’s Republic of Korea',
'UK-DRC': 'UK sanctions relating to the Democratic Republic of the Congo',
'UK-BLR': 'UK sanctions relating to the Republic of Belarus',
'UK-GNB': 'UK sanctions relating to the Republic of Guinea-Bissau',
'UK-DRILL': 'UK sanctions relating to unauthorized drilling activities',
'UK-VEN': 'UK sanctions relating to Venezuela',
'UK-YEM': 'UK sanctions relating to Yemen',
'UK-ZIM': 'UK sanctions relating to Zimbabwe',
'gb_hmt_invbans': 'UK HMT/OFSI Investment Bans',
'gb_nca_most_wanted': 'UK NCA Most Wanted',
'gb_proscribed_orgs': 'UK Proscribed Terrorist Groups or Organizations',
'ext_ua_edr': 'Ukraine Consolidated State Registry',
'ua_nsdc_sanctions': 'Ukraine NSDC State Register of Sanctions',
'UA-SA1644': 'Law of Ukraine "On Sanctions" No. 1644-VII dated 14 Aug. 2014',
'ua_sfms_blacklist': 'Ukraine SFMS Blacklist',
'un_ga_protocol': 'UN Heads of State, Heads of Government and Ministers for Foreign Affairs',
'un_sc_sanctions': 'UN Security Council Consolidated Sanctions',
'UN-SC2713': 'Al-Shabaab Sanctions ',
'UN-SC2127': 'Central African Republic Sanctions',
'UN-SC1533': 'Democratic Republic Of Congo Sanctions',
'UN-SC2048': 'Guinea-Bissau Sanctions',
'UN-SC2653': 'Haiti Sanctions ',
'UN-SC1518': 'Iraq Sanctions',
'UN-SCISIL': 'ISIL & Al-Qaida Sanctions',
'UN-SC-1267': 'Islamic State In Iraq And The Levant (Da’esh), Al-Qaida And Associated Individuals',
'UN-SC1970': 'Libya Sanctions',
'UN-SC1718': 'North Korea Sanctions',
'UN-SC1636': 'Rafiq Hariri Killing Sanctions',
'UN-SC2206': 'South Sudan Sanctions ',
'UN-SC1591': 'Sudan Sanctions',
'UN-SC1988': 'Taliban Sanctions',
'UN-SC2140': 'Yemen Sanctions',
'ae_local_terrorists': 'United Arab Emirates Local Terrorist List',
'us_plum_book': 'United States Periodically Listing Updates to Management (PLUM) Reporting',
'uy_pep': 'Uruguayan Politically Exposed Persons (PEP)',
'us_ak_med_exclusions': 'US Alaska Medical Assistance Excluded Provider List',
'us_klepto_hr_visa': 'US Anti-Kleptocracy and Human Rights Visa Restrictions',
'us_az_med_exclusions': 'US Arizona Medicaid Suspensions and Terminations',
'us_ar_med_exclusions': 'US Arkansas Medicaid Excluded Provider List',
'us_bis_denied': 'US BIS Denied Persons List',
'us_ca_med_exclusions': 'US California Medicaid Suspended and ineligible providers',
'us_cbp_forced_labor': 'US CBP Withhold Release Orders and Findings',
'us_cia_world_factbook': 'US CIA World Factbook Heads of State and Government',
'us_cia_world_leaders': 'US CIA World Leaders',
'us_co_med_exclusions': 'US Colorado Medicaid Terminated Provider List',
'us_dea_fugitives': 'US DEA Fugitives',
'us_state_terrorist_exclusion': 'US Department of State Terrorist Exclusion',
'us_ddtc_debarred': 'US Directorate of Defense Trade Controls AECA Debarments',
'us_ddtc_enforcements': 'US Directorate of Defense Trade Controls Penalties & Oversight Agreements',
'us_dod_chinese_milcorps': 'US DoD Chinese military companies',
'US-DOD-1260H': 'Chinese Military Companies Sanctions (1260H)',
'us_fbi_lazarus_crypto': 'US FBI Lazarus Group Crypto Wallets',
'us_fbi_most_wanted': 'US FBI Most Wanted',
'us_fcc_covered_list': 'US FCC Covered List',
'US-FCC': 'List of Equipment and Services Covered By Section 2 of The Secure Networks Act',
'us_fdic_failed_banks': 'US FDIC Failed Banks',
'us_fed_enforcements': 'US Federal Reserve Enforcement Actions',
'US-FED-ENF': 'US Federal Reserve Enforcement Actions',
'us_fincen_special_measures': 'US FinCEN 311 and 9714 Special Measures',
'us_finra_actions': 'US FINRA Enforcement Actions',
'us_ga_med_exclusions': 'US Georgia Healthcare provider exclusions',
'us_hi_med_exclusions': 'US Hawaii Medicaid Exclusions and Reinstatements',
'us_hhs_exclusions': 'US Health and Human Sciences Inspector General Exclusions',
'us_in_med_exclusions': 'US Indiana Medicaid Terminated Provider List',
'us_ia_med_exclusions': 'US Iowa Medicaid Terminated Provider List',
'us_ks_med_exclusions': 'US Kansas Medicaid Terminated Provider List',
'us_ky_med_exclusions': 'US Kentucky Terminated and Excluded Providers',
'us_plural_legislators': 'US Legislators by Plural (formerly OpenStates)',
'us_la_med_exclusions': 'US Louisiana Department of Health Adverse Actions List',
'us_md_med_exclusions': 'US Maryland Sanctioned Providers',
'us_ma_med_exclusions': 'US Massachusetts Suspensions and Exclusions from MassHealth',
'us_congress': 'US Members of the Congress',
'us_mi_med_exclusions': 'US Michigan Medicaid Sanctioned Provider List',
'us_mn_med_exclusions': 'US Minnesota Health Care Programs Excluded Providers',
'us_ms_med_exclusions': 'US Mississippi Medicaid Terminated Provider List',
'us_mo_med_exclusions': 'US Missouri Medicaid Provider Terminations',
'us_mt_med_exclusions': 'US Montana Medicaid Excluded and Terminated Providers',
'us_navy': 'US Navy Leadership',
'us_nv_med_exclusions': 'US Nevada Medicaid Sanctions',
'us_nh_med_exclusions': 'US New Hampshire Medicaid Exclusion and Sanction List',
'us_nj_med_exclusions': 'US New Jersey Ineligible Medicaid Providers',
'us_ny_med_exclusions': 'US New York State Medicaid Exclusions',
'us_nc_med_exclusions': 'US North Carolina Excluded Providers List',
'us_nd_med_exclusions': 'US North Dakota Medicaid Terminated Provider List',
'us_occ_enfact': 'US OCC Enforcement Actions',
'us_ofac_cons': 'US OFAC Consolidated (non-SDN) List',
'US-BURMA': 'Burma-Related Sanctions',
'US-CHINA-MIL': 'Chinese Military Companies Sanctions',
'US-FSE': 'Foreign Sanctions Evaders (FSE) List',
'US-NS-CMIC': 'Non-SDN Chinese Military-Industrial Complex Companies',
'US-NS-PLC': 'Palestinian Legislative Council',
'US-SSI': 'Sectoral Sanctions Identifications (SSI) List',
'us_ofac_sdn': 'US OFAC Specially Designated Nationals (SDN) List',
'US-AFGH': 'Afghanistan-Related Sanctions',
'US-BALKANS': 'Balkans-Related Sanctions',
'US-BRUS': 'Belarus Sanctions',
'US-CAR': 'Central African Republic Sanctions',
'US-NARCO': 'Counter Narcotics Trafficking Sanctions',
'US-TERR': 'Counter Terrorism',
'US-CUBA': 'Cuba Sanctions ',
'US-CYB': 'Cyber-Related Sanctions',
'US-DRC': 'Democratic Republic Of The Congo-Related Sanctions',
'US-ETHIOPIA': 'Ethiopia-Related Sanctions ',
'US-FORINT': 'Foreign Interference In A United States Election Sanctions',
'US-GLOMAG': 'Global Magnitsky Sanctions',
'US-HONGKONG': 'Hong Kong-Related Sanctions',
'US-HOSTAGE': 'Hostages And Wrongfully Detained U.S. Nationals Sanctions',
'US-IRAN': 'Iran Sanctions ',
'US-IRAQ': 'Iraq-Related Sanctions',
'US-LEBANON': 'Lebanon-Related Sanctions',
'US-LIBYA': 'Libya Sanctions',
'US-MAGNITSKY': 'Magnitsky Sanctions',
'US-MALI': 'Mali-Related Sanctions',
'US-NICARAGUA': 'Nicaragua-Related Sanctions',
'US-NON-PROLIF': 'Non-Proliferation Sanctions',
'US-NK': 'North Korea Sanctions',
'US-RUSHAR': 'Russian Harmful Foreign Activities Sanctions',
'US-SOMALIA': 'Somalia Sanctions (EO 13620, EO 13536)',
'US-SOUTH-SUDAN': 'South Sudan-Related Sanctions (EO 13664)',
'US-DARFUR': 'Sudan and Darfur Sanctions',
'US-SYR-REL': 'Syria-Related Sanctions (EO 13894)',
'US-SYR': 'Syria Sanctions (EO 13608 et al.)',
'US-TCO': 'Transnational Criminal Organizations',
'US-UKRRUS-REL': 'Ukraine-/Russia-Related Sanctions',
'US-VEN': 'Venezuela-Related Sanctions',
'US-YEMEN': 'Yemen-Related Sanctions (EO 13611)',
'us_bis_oac': 'US Office of Antiboycott Compliance Requester List',
'us_oh_med_exclusions': 'US Ohio Medicaid Excluded and Suspended Providers',
'us_or_med_exclusions': 'US Oregon State Medicaid Fraud Convictions',
'us_pa_med_exclusions': 'US Pennsylvania Medicheck list',
'us_sec_pause': 'US Public Alert: Unregistered Soliciting Entities (PAUSE)',
'us_sam_exclusions': 'US SAM Procurement Exclusions',
'us_sec_harmed_investors': 'US SEC Actions Due to Harmed Investors',
'us_ss_wanted': 'US Secret Service Most Wanted Fugitives',
'us_sc_med_exclusions': 'US South Carolina Excluded Providers',
'us_special_leg': 'US Special Legislative Exclusions',
'US-5949LIST': 'James M. Inhofe National Defense Authorization Act (5949 List)',
'US-MCCAIN-899': 'John S. McCain National Defense Authorization Act for Fiscal Year 2019 (899 List)',
'US-MCCAIN-1286': 'Section 1286 of the John S. McCain National Defense Authorization Act for Fiscal Year 2019 (Public Law 115 - 232)',
'US-CORRUPT-353': 'Section 353 of the Corrupt and Undemocratic Actors Report',
'us_cuba_sanctions': 'US State Department Cuba Sanctions',
'US-DOS-CU-PAL': 'Cuba Prohibited Accommodations List',
'US-DOS-CU-REA': 'List of Restricted Entities and Subentities Associated With Cuba',
'us_state_dept': 'US State Department Senior Officials',
'us_tn_med_exclusions': 'US Tennessee Terminated Providers List',
'us_trade_csl': 'US Trade Consolidated Screening List (CSL)',
'US-AECA-DEBARRED': 'AECA Debarred List',
'US-BIS-DPL': 'BIS Denied Persons List (DPL)',
'US-BIS-EL': 'BIS Entity List (EL)',
'US-BIS-MEU': 'BIS Military End-Users (MEU) List',
'US-BIS-UVL': 'BIS Unverified List',
'us_dhs_uflpa': 'US UFLPA Entity List',
'US-UFLPA': 'Uyghur Forced Labor Prevention Act (Public Law No. 117-78)',
'us_wa_med_exclusions': 'US Washington State Provider Termination and Exclusion List',
'us_wv_med_exclusions': 'US West Virginia Medicaid Provider Exclusions and Terminations',
'us_wy_med_exclusions': 'US Wyoming Medicaid Provider Exclusion List',
've_asamblea_nacional': 'Venezuela Members of the National Assembly',
'wikidata': 'Wikidata',
'wd_curated': 'Wikidata Entities of Interest',
'wd_categories': 'Wikidata Persons in Relevant Categories',
'wd_peps': 'Wikidata Politically Exposed Persons',
'worldbank_debarred': 'WorldBank Debarred Providers',
'': 'undefined',
};

export const getDataSourcesLabel = (dataSourceCode) => {
  if (!dataSourceCode) return 'Non spécifié';
  const code = String(dataSourceCode).toLowerCase();
  return dataSourcesMappings[code] || dataSourceCode;
};

// Fonction pour obtenir la liste complète des data sources
export const getDataSourcesList = () => {
  return Object.entries(dataSourcesMappings).map(([code, label]) => ({
    code,
    label
  }));
};